DROP TABLE IF EXISTS `real_estate`;
CREATE TABLE `real_estate` (
  `real_estate_id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) DEFAULT NULL,
  `price` decimal(20,2) DEFAULT NULL,
  `currency` varchar(10) DEFAULT NULL,
  `title` varchar(150) DEFAULT NULL,
  `description` text,
  `size` int(11) DEFAULT NULL,
  `city` varchar(100) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `region` varchar(100) DEFAULT NULL,
  `neighborhood` varchar(100) DEFAULT NULL,
  `longitude` double DEFAULT NULL,
  `latitude` double DEFAULT NULL,
  `type` varchar(50) DEFAULT NULL,
  `sub_type` varchar(50) DEFAULT NULL,
  `purpose` varchar(50) DEFAULT NULL,
  `rooms_number` tinyint(4) DEFAULT NULL,
  `bath_numbers` tinyint(4) DEFAULT NULL,
  `object` json DEFAULT NULL,
  `street` varchar(255) DEFAULT NULL,
  `status` varchar(50) DEFAULT 'available',
  `created_by` varchar(50) DEFAULT NULL,
  `last_updated_by` varchar(50) DEFAULT NULL,
  `created_date` datetime DEFAULT NOW(),
  `updated_date` datetime DEFAULT NULL,
  PRIMARY KEY (`real_estate_id`),
  KEY `user_id` (`user_id`),
  KEY `idx_price` (`price`),
  KEY `idx_created_date` (`created_date`),
  CONSTRAINT `real_estate_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;